/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResultRouteImport } from './routes/result'
import { Route as JamRouteImport } from './routes/jam'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as JamCodeRouteImport } from './routes/jam.$code'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const JamRoute = JamRouteImport.update({
  id: '/jam',
  path: '/jam',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const JamCodeRoute = JamCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => JamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/jam': typeof JamRouteWithChildren
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/jam/$code': typeof JamCodeRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/jam': typeof JamRouteWithChildren
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/jam/$code': typeof JamCodeRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/jam': typeof JamRouteWithChildren
  '/result': typeof ResultRoute
  '/scan': typeof ScanRoute
  '/jam/$code': typeof JamCodeRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/jam'
    | '/result'
    | '/scan'
    | '/jam/$code'
    | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/jam'
    | '/result'
    | '/scan'
    | '/jam/$code'
    | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/jam'
    | '/result'
    | '/scan'
    | '/jam/$code'
    | '/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  JamRoute: typeof JamRouteWithChildren
  ResultRoute: typeof ResultRoute
  ScanRoute: typeof ScanRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jam': {
      id: '/jam'
      path: '/jam'
      fullPath: '/jam'
      preLoaderRoute: typeof JamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jam/$code': {
      id: '/jam/$code'
      path: '/$code'
      fullPath: '/jam/$code'
      preLoaderRoute: typeof JamCodeRouteImport
      parentRoute: typeof JamRoute
    }
  }
}

interface JamRouteChildren {
  JamCodeRoute: typeof JamCodeRoute
}

const JamRouteChildren: JamRouteChildren = {
  JamCodeRoute: JamCodeRoute,
}

const JamRouteWithChildren = JamRoute._addFileChildren(JamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  JamRoute: JamRouteWithChildren,
  ResultRoute: ResultRoute,
  ScanRoute: ScanRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
